### PR TITLE
Use a Jekyll collection to add signatures

### PR DESCRIPTION
**Pull request by emhoracek**
You can see what this will look like on my [GitHub page](https://emhoracek.github.io/microsoft-drop-ice/). 

There are a lot of files here! A lot of it is because I had to copy in all the theme files -- Github Pages wasn't compiling the CSS correctly. I'll see if I can remove anything unnecessary.

Maybe try out the signature flow on [my fork](https://github.com/emhoracek/microsoft-drop-ice) and see if you're happy with how it works.

### CODE REVIEW

**Comment by selfagency** [comment]
thanks, will pull this locally and give it a go.

**Comment by komali2** [comment]
Can't you rebase and clean up some of the commits? Or do a new pr with a cleaner history?

**Comment by selfagency** [comment]
@komali2 your input is welcome and appreciated, but what's your concern precisely? does it really matter to potential signatories if a simple petition has a long commit history?

**Comment by emhoracek** [comment]
Feel free to squash 'n' merge

**Comment by komali2** [comment]
@selfagency nah fam, just like it doesn't really matter if I make my bed in the morning lol. Just like, it's easy and looks better, so why not?

**Comment by synox** [comment]
Why sooo complicated when a simple Readme works great?

**Comment by selfagency** [comment]
what about a bot? couldn't we make some kind of serverless function that gets passed a webhook and then just grabs whatever's been inserted and sticks it at the bottom of the signatories list and then uses the github api to merge the PR? that would be a handy tool for github petitions, no?

**Comment by emhoracek** [comment]
I went ahead an removed some excess stuff that Jekyll includes by default. Diff is now less than 200 lines. 

It seems this petition isn't getting such a volume of signatures that merge conflicts are a huge problem, so it's true that even this little PR may be over-engineering. I don't want to make a bot, but if that sounds fun to you go for it.

**Comment by dessalines** [comment]
This is pretty pointless IMO. The readme is much faster and better.

**Comment by selfagency** [comment]
@emhoracek I greatly appreciate the work you've done, Libby. Thank you for your help. I am going to close this for now unless the volume of signatures becomes to unwieldy to manage manually.

**Pull request closed without merging**
