### PR TITLE
Please Add Me

### PR DESCRIPTION
**Pull request by codeslingerMalthius**

### CODE REVIEW

**Comment by jamiebuilds** [comment]
Please click the button in the sidebar to allow edits on your branch

**Comment by codeslingerMalthius** [comment]
I don't see a button like that. Can you please let me know what it looks like?

**Comment by selfagency** [comment]
@codeslingerMalthius [see here](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)

**Comment by selfagency** [comment]
ah i'll just add you manually, whatever.

**Pull request closed without merging**
