### PR TITLE
Add Aleph folks to list.

### PR DESCRIPTION
**Pull request by oppodeldoc**

### CODE REVIEW

**Comment by benwiley4000** [comment]
I think it would be best to have folks commit their names themselves - otherwise unclear who actually consented to be on the list.

**Comment by selfagency** [comment]
you can have them comment here to confirm their signatures

**Comment by oppodeldoc** [comment]
Hey there, sorry for any confusion but Jasmine added her own signature with her own username @jennessy in this commit https://github.com/selfagency/microsoft-drop-ice/pull/185/commits/7b398643d59efe24143bcf67ba2ff989826037a6

It might have been wiped out because I had to re-arrange stuff since the file changed a ton after alphabetizing and adding new names this morning. @jennessy can you quickly confirm that you assented to signing this?

**Comment by selfagency** [comment]
based on her PR, i can just confirm and merge

**Comment by jennessy** [comment]
Hi, I can confirm that I added my own signature. Thanks!

**Comment by benwiley4000** [comment]
My bad, I just realize the other two folks you touched were just space deletions, not new names. False alarm!

**Pull request merged**
